apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline

spec:
  params:
    - name: repo-url

    - name: branch
      default: "master"

    - name: build-image

  workspaces:
    - name: pipeline-workspace

  tasks:
    - name: clone
      taskRef:
        name: checkout
      params:
        - name: repo-url
          value: "$(params.repo-url)"

        - name: branch
          value: "$(params.branch)"

    - name: lint
      runAfter:
        - clone
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: image
          value: "python:3.9-slim"

        - name: args
          value:
            - "--count"
            - "--max-complexity=10"
            - "--max-line-length=127"
            - "--statistics"

    - name: tests
      runAfter:
        - lint
      taskRef:
        name: echo
      params:
        - name: message
          value: "Running unit tests with PyUnit..."

    - name: build
      runAfter:
        - tests
      taskRef:
        name: buildah
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: IMAGE
          value: "$(params.build-image)"

    - name: deploy
      runAfter:
        - build
      taskRef:
        name: echo
      params:
        - name: message
          value: "Deploying $(params.branch) branch of $(params.repo-url) ..."